# Form implementation generated from reading ui file 'src/carereport/views/dietline.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dietLineDialog(object):
    def setupUi(self, dietLineDialog):
        dietLineDialog.setObjectName("dietLineDialog")
        dietLineDialog.resize(492, 587)
        self.layoutWidget = QtWidgets.QWidget(parent=dietLineDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 240, 441, 268))
        self.layoutWidget.setObjectName("layoutWidget")
        self.DietLineLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.DietLineLayout.setContentsMargins(6, 6, 6, 6)
        self.DietLineLayout.setObjectName("DietLineLayout")
        self.FoodNameLabelabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.FoodNameLabelabel.setObjectName("FoodNameLabelabel")
        self.DietLineLayout.addWidget(self.FoodNameLabelabel, 0, 1, 1, 1)
        self.descriptionLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.DietLineLayout.addWidget(self.descriptionLabel, 2, 1, 1, 1)
        self.DescriptionEdit = QtWidgets.QTextEdit(parent=self.layoutWidget)
        self.DescriptionEdit.setObjectName("DescriptionEdit")
        self.DietLineLayout.addWidget(self.DescriptionEdit, 2, 2, 1, 1)
        self.FoodNameEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.FoodNameEdit.setObjectName("FoodNameEdit")
        self.DietLineLayout.addWidget(self.FoodNameEdit, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.DietLineLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.DietLineLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.applicationTypeLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.applicationTypeLabel.setObjectName("applicationTypeLabel")
        self.DietLineLayout.addWidget(self.applicationTypeLabel, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.DietLineLayout.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.dietLineTable = QtWidgets.QTableWidget(parent=dietLineDialog)
        self.dietLineTable.setGeometry(QtCore.QRect(35, 20, 431, 192))
        self.dietLineTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.dietLineTable.setColumnCount(2)
        self.dietLineTable.setObjectName("dietLineTable")
        self.dietLineTable.setRowCount(0)
        self.dietLineTable.verticalHeader().setVisible(False)
        self.resetButton = QtWidgets.QPushButton(parent=dietLineDialog)
        self.resetButton.setGeometry(QtCore.QRect(359, 520, 118, 26))
        self.resetButton.setShortcut("")
        self.resetButton.setAutoDefault(False)
        self.resetButton.setObjectName("resetButton")
        self.closeButton = QtWidgets.QPushButton(parent=dietLineDialog)
        self.closeButton.setGeometry(QtCore.QRect(30, 520, 85, 26))
        self.closeButton.setShortcut("")
        self.closeButton.setAutoDefault(False)
        self.closeButton.setDefault(True)
        self.closeButton.setObjectName("closeButton")
        self.statusMessageLabel = QtWidgets.QLabel(parent=dietLineDialog)
        self.statusMessageLabel.setGeometry(QtCore.QRect(20, 560, 471, 20))
        self.statusMessageLabel.setObjectName("statusMessageLabel")
        self.newLineButton = QtWidgets.QPushButton(parent=dietLineDialog)
        self.newLineButton.setGeometry(QtCore.QRect(210, 520, 120, 26))
        self.newLineButton.setAutoDefault(False)
        self.newLineButton.setObjectName("newLineButton")

        self.retranslateUi(dietLineDialog)
        QtCore.QMetaObject.connectSlotsByName(dietLineDialog)

    def retranslateUi(self, dietLineDialog):
        _translate = QtCore.QCoreApplication.translate
        dietLineDialog.setWindowTitle(_translate("dietLineDialog", "- Beschrijf regels"))
        self.FoodNameLabelabel.setText(_translate("dietLineDialog", "Voeding"))
        self.descriptionLabel.setText(_translate("dietLineDialog", "Beschrijving"))
        self.applicationTypeLabel.setText(_translate("dietLineDialog", "Regel"))
        self.resetButton.setText(_translate("dietLineDialog", "On&gedaan maken"))
        self.closeButton.setText(_translate("dietLineDialog", "&Sluit venster"))
        self.statusMessageLabel.setText(_translate("dietLineDialog", "Klaar"))
        self.newLineButton.setText(_translate("dietLineDialog", "&Nieuwe dieetregel"))
