# Form implementation generated from reading ui file 'src/carereport/views/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu_Bestand = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Bestand.setObjectName("menu_Bestand")
        self.menuI_ntake = QtWidgets.QMenu(parent=self.menubar)
        self.menuI_ntake.setObjectName("menuI_ntake")
        self.menu_Pati_nt = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Pati_nt.setObjectName("menu_Pati_nt")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAfsluiten = QtGui.QAction(parent=MainWindow)
        self.actionAfsluiten.setMenuRole(QtGui.QAction.MenuRole.QuitRole)
        self.actionAfsluiten.setObjectName("actionAfsluiten")
        self.action_Nieuw = QtGui.QAction(parent=MainWindow)
        self.action_Nieuw.setObjectName("action_Nieuw")
        self.actionAanpassen = QtGui.QAction(parent=MainWindow)
        self.actionAanpassen.setObjectName("actionAanpassen")
        self.actionPatientZoeken = QtGui.QAction(parent=MainWindow)
        self.actionPatientZoeken.setObjectName("actionPatientZoeken")
        self.actionNieuw = QtGui.QAction(parent=MainWindow)
        self.actionNieuw.setObjectName("actionNieuw")
        self.menu_Bestand.addAction(self.actionAfsluiten)
        self.menuI_ntake.addAction(self.actionNieuw)
        self.menuI_ntake.addAction(self.actionAanpassen)
        self.menu_Pati_nt.addAction(self.actionPatientZoeken)
        self.menubar.addAction(self.menu_Bestand.menuAction())
        self.menubar.addAction(self.menuI_ntake.menuAction())
        self.menubar.addAction(self.menu_Pati_nt.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Zorg rapportage"))
        self.menu_Bestand.setTitle(_translate("MainWindow", "&Bestand"))
        self.menuI_ntake.setTitle(_translate("MainWindow", "I&ntake"))
        self.menu_Pati_nt.setTitle(_translate("MainWindow", "&Patiënt"))
        self.actionAfsluiten.setText(_translate("MainWindow", "A&fsluiten"))
        self.actionAfsluiten.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_Nieuw.setText(_translate("MainWindow", "&Nieuw"))
        self.action_Nieuw.setShortcut(_translate("MainWindow", "Backspace, Backspace"))
        self.actionAanpassen.setText(_translate("MainWindow", "&Aanpassen"))
        self.actionPatientZoeken.setText(_translate("MainWindow", "&Zoeken"))
        self.actionPatientZoeken.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionNieuw.setText(_translate("MainWindow", "N&ieuw"))
        self.actionNieuw.setShortcut(_translate("MainWindow", "Ctrl+N"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
